config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'

  post 'person/upload_avatar' => 'person#upload_avatar', as: :upload_avatar

end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  belongs_to :user

  validates :text, presence: true, length: { maximum: 128 }

  def created_at_ago
    time_ago_in_words(created_at)
  end

  def avatar_mini
    user.avatar.url
  end

  def as_json(options = nil)
    super((options || {}).merge({ only: [:text], methods: [:created_at_ago],
                                  include: { user: { only: [ :email, :username, :avatar] } } }))
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :uniqueness => { :case_sensitive => false }
  validate :avatar_file_size

  mount_uploader :avatar, AvatarUploader

  has_many :posts

  scope :online, -> { where online: true }

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def avatar_file_size
    if avatar.file && avatar.file.size.to_f > 1024 * 100
      errors.add(:file_size, "You cannot upload a file greater than 100KB.")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController

  after_filter :update_online_list, only: [ :client_connected, :client_disconnected ]

  def initialize_session
    # perform application setup here
    controller_store[:message_count] = 0
  end

  def get_posts
    posts = Post.last(50)
    trigger_success posts
  end

  def new_post
    post = Post.new(text: message["text"])
    post.user = current_user
    if post.save
      WebsocketRails[:posts].trigger "append_post", post
    else
      trigger_failure  reason: "the post is incorrect"
    end
  end

  def online_users
    trigger_success User.online
  end

  def client_disconnected
    current_user.online = false
    current_user.save
  end

  def client_connected
    current_user.online = true
    current_user.save
  end


  private

  def update_online_list
    WebsocketRails[:posts].trigger "update_online_list", User.online
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def upload_avatar
    current_user.avatar = params[:user][:avatar]
    if current_user.save
      flash[:success] = "Your avatar has been updated successfully."
    else
      flash[:warning] ||= current_user.errors[:file_size][0]
    end
    redirect_to controller: :main, action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="row header">
  <div class="small-12 small-centered medium-8 medium-centered large-8 large-centered columns">
    <%= image_tag "tiger.png", width: 100, height: 100 %>
    <div class="title">Funny chat</div>
    <div class="menu">
      <% if signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %> |
          <%= current_user.username if signed_in? %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Funny chat" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/main/_chat.html.erb
<div id="chat" class="chat">
  <div id="history" class="history"></div>
  <label for="text">Message</label>
  <textarea id="text" rows="3" maxlength="128" placeholder="Input message..." autofocus></textarea>
  <input type="button" id="send" class="button radius" value="Send message"/>
</div>

app/views/main/_online.html.erb
<nav class="online">
  <ul>
    <li><span id="users_count"></span> <i class="glyphicon glyphicon-user"><span> online</span></i>
      <ul id="users_list">
      </ul>
    </li>
  </ul>
</nav>

app/views/main/_person.html.erb
<div id="person">
  <div class="avatar-view">
    <%= image_tag(current_user.avatar.url || "default_avatar.png", size: "200x200") %>
    <div class="mask">
      <div class="upload-action">
        <i class="glyphicon glyphicon-arrow-up"></i>
        <span>Upload avatar</span>
      </div>
    </div>
  </div>

  <!-- <div class="switch tiny">
    <input id="exampleCheckboxSwitch" type="checkbox">
    <label for="exampleCheckboxSwitch"></label>
  </div>
  <i class="glyphicon glyphicon-eye-open"></i> -->

  <%= form_tag(upload_avatar_path, multipart: true, class: "upload", id: "upload") do %>
      <p>
        <label>My Avatar</label>
        <%= file_field(:user, :avatar, accept: "image/jpeg,image/png,image/jpg" ) %>
        <%= submit_tag "Ok", class: "button" %>
      </p>
  <% end %>
</div>

app/views/main/index.html.erb
<% content_for :title, "Funny chat" %>

<div class="row">
  <div class="small-12 small-centered medium-8 medium-centered large-8 large-centered columns">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, data: { alert: nil }, class: "alert-box #{name} radius" do %>
        <%= msg %>
        <a href="#" class="close">&times;</a>
      <% end %>
    <% end %>

    <div class="row">
      <div class="hide-for-small-only medium-12 large-12 columns">
        <%= render "main/online" %>
      </div>
    </div>

    <div class="hide-for-small-only hide-for-medium-only large-4 columns">
      <%= render "main/person" %>
    </div>
    <div class="small-12 medium-12 large-8 columns">
      <%= render "main/chat" %>
    </div>
  </div>
</div>